---
- name: Verifica Jenkins raggiungibile
  ansible.builtin.uri:
    url: "{{ jenkins_agent_controller_url }}"
    user: "{{ jenkins_agent_admin_user }}"
    password: "{{ jenkins_agent_admin_token }}"
    force_basic_auth: true
    status_code: 200
  register: jenkins_agent_check
  retries: 15
  delay: 18
  until: jenkins_agent_check.status == 200

- name: Crea container Jenkins Agent
  community.docker.docker_container:
    name: "{{ jenkins_agent_name }}"
    image: jenkins/inbound-agent:latest
    state: started
    restart_policy: always

    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - name: network1

    env:
      JENKINS_URL: "{{ jenkins_agent_controller_url }}"
      JENKINS_SECRET: "{{ jenkins_agent_secret }}"
      JENKINS_AGENT_NAME: "{{ jenkins_agent_name }}"
      JENKINS_AGENT_WORKDIR: "{{ jenkins_agent_workdir }}"
