def buildAndPushTag(Map args) {
	def defaults = [
		registryUrl: 'https://index.docker.io/v1/',
		dockerfileDir: "./",
		dockerfileName: "Dockerfile", 
		buildArgs: "",
		pushLatest: false 
	]

	args = defaults + args 

	docker.withRegistry(args.registryUrl, 'dockerhub-credentials') {
		def image = docker.build(
			args.image,
		    	"${args.buildArgs} ${args.dockerfileDir} -f ${args.dockerfileName}"
		)

		image.push(args.buildTag)

		if(args.pushLatest) {
			image.push("latest")
			sh "docker rmi --force ${args.image}:latest"
		} 

		sh "docker rmi --force ${args.image}:${args.buildTag}"

		return "${args.image}:${args.buildTag}"
	}
}



pipeline {
	agent any 

	stages {
		stage('Set Docker Tag') {
			steps {
				script {
					if (env.TAG_NAME) {
						env.DOCKER_TAG = env.TAG_NAME 
					} else if (env.BRANCH_NAME == 'main') {
						env.DOCKER_TAG = 'latest' 
					} else if (env.BRANCH_NAME == 'develop') {
						def sha = sh( 
							script: 'git rev-parse --short HEAD', 
							returnStdout: true
						).trim()
						env.DOCKER_TAG = "develop-${sha}" 
					} else { 
						def sha = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim() 
						def safeBranch = env.BRANCH_NAME.replaceAll(/[^a-zA-Z0-9-_]/, '-')
						env.DOCKER_TAG = "${safeBranch}-${sha}"
					}
				}
			}
		}

		stage('Build and Push') {
			steps {
			    script {
				    buildAndPushTag(
				        image: "robertasou/flask-app-example",
					buildTag: env.DOCKER_TAG,
					pushLatest: env.BRANCH_NAME == 'main' 
				    )
			    }
		    }
	    }
        //stage('Build') {
           //steps {
                //sh 'docker build -t flask-app-example ./Step2'
            //}
       // }

        //stage('Push') {
            //steps {
                //withCredentials([usernamePassword(
                    //credentialsId: 'dockerhub-credentials',
                    //usernameVariable: 'DOCKER_USER',
                    //passwordVariable: 'DOCKER_TOKEN'
                //)]) {
                    //sh 'echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin'
                    //sh 'docker tag flask-app-example robertasou/flask-app-example:latest'
                    //sh 'docker push robertasou/flask-app-example:latest'
                //}
            //}
        //}
    }
}
